baseURL = 'https://test.jobcher.com'
theme = "blog-theme"
languageCode = 'en-us'
title = '打工人日志'
# 相对地址
relativeURLs = true

# 显示数量
paginate = 15  #每页显示行数
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

# 代码高亮
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[[menu.main]]
identifier="1"
name="首页"
url="/"
weight="1"
[[menu.main]]
name="文章"
url="/posts"
weight="2"
#[[menu.main]]
#name="新闻"
#url="/news"
#weight="3"
[[menu.main]]
name="导航"
url="https://nav.jobcher.com/"
weight="4"
[[menu.main]]
name="关于"
url="/posts/about"
weight="5"


[[menu.foot]]
name="网站首页"
url="/"
weight="4"
[[menu.foot]]
name="博文合集"
url="/posts"
weight="3"
#[[menu.foot]]
#name="新闻列表"
#weight="2"
[[menu.foot]]
name="关于我们"
url="/posts/about"
weight="1"

